# Generated by Django 5.1.3 on 2024-11-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_creatorprofilemodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='Icon',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='Price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
