# Generated by Django 5.1.3 on 2024-11-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_coursemodel_icon_alter_coursemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='Icon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
