# Generated by Django 5.1.3 on 2024-11-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='author_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('about_author', models.TextField(max_length=1000, null=True)),
                ('Image', models.ImageField(null=True, upload_to='Media/author_Pic')),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_model',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='Image',
            new_name='featured_image',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='Course_Description',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='Icon',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='featured_video',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='status',
            field=models.CharField(choices=[('publish', 'PUBLISH'), ('draft', 'DRAFT')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.author_profile'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category_model'),
        ),
    ]
