# Generated by Django 5.1.3 on 2024-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_author_profile_rename_category_category_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
