# Generated by Django 5.1.3 on 2024-11-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_coursemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_profile',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author_profile',
            name='detailed_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author_profile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author_profile',
            name='field_of_expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author_profile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='author_profile',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
