# Generated by Django 5.1.3 on 2024-11-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_lesson_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('Price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('publish', 'PUBLISH'), ('draft', 'DRAFT')], max_length=255, null=True)),
                ('featured_image', models.ImageField(null=True, upload_to='Media/Course_Pic')),
                ('featured_video', models.CharField(max_length=200, null=True)),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.author_profile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category_model')),
            ],
        ),
    ]
