# Generated by Django 5.1.3 on 2024-11-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_courseeemodel_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseeemodel',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.video'),
        ),
    ]
