# Generated by Django 5.1 on 2024-11-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='author',
            name='video',
        ),
    ]
