# Generated by Django 5.1 on 2024-11-19 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_author_lesson_remove_author_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='only',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.author')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.courseeemodel')),
            ],
        ),
    ]
