# Generated by Django 5.1 on 2024-12-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_only_only1_only2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='only2',
        ),
    ]
