# Generated by Django 5.1 on 2025-01-14 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_only2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofilemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creatorProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
