# Generated by Django 5.1 on 2025-01-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_creatorprofilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_profile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category_model'),
        ),
    ]
