# Generated by Django 5.1 on 2025-01-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_author_profile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_profile',
            name='category',
        ),
    ]
