# Generated by Django 5.1 on 2025-01-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_author_profile_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='user_type',
            new_name='usertype',
        ),
    ]
